ISA*${AuthorizationInformationQualifier}*${AuthorizationInformation}*${SecurityInformationQualifier}*${SecurityInformation}*${InterchangeIDQualifierSender}*${InterchangeSenderID}*${InterchangeIDQualifier}*${InterchangeIDQualifierSender}*${InterchangeSenderID}*${InterchangeIDQualifier}*${InterchangeReceiverID}*${InterchangeDate}*${InterchangeTime}*${InterchangeControlStandardsIdentifier}*${InterchangeControlVersionNumber}*${InterchangeControlNumber}*${AcknowledgementRequested}*${TestIndicator}*>~
GS*PR*${ApplicationSenderCode}*${ApplicationReceiverCode}*${Date}*${Time}*${GroupControlNumber}*${ResponsibleAgencyCode}*${Version}~
ST*810*${TransactionSetControlNumber}~
BIG*${InvoiceIssueDate}*${InvoiceNumber}*${PurchaseOrderDate}*${PurchaseOrderNumber}~
REF*${ReferenceIdentificationQualifier}*${InvoiceNumber}~
ITD************${DescriptionsOfTerms}~
DTM*${DateQualifier}*${Date}~
IT1**${QuantityInvoiced}*${UnitOfMeasure}*${UnitPrice}**${ProductIDQualifier}*${ProductID}*${ProductIDQualifier2}*${ProductID2}~
PID*${ItemDescriptionType}****${Description}~
TDS${TotalAmount}~
CAD*****${CarrierDescription}****${ReferenceIdentificationQualifier}~
SAC*${ServiceChargeIndicator}*${ServiceChargeCode}***${ServiceFreightAmount}~
SAC*${EnvironmentalChargeIndicator}*${EnvironmentalChargeCode}***${EnvironmentalFreightAmount}~
SAC*${TaxesChargeIndicator}*${TaxesChargeCode}***${TaxesFreightAmount}~
TXI*${TaxCodeType}*${TaxAmount}~
ISS*${NumberOfUnitsShipped}*${UnitOfMeasure}*${Weight}*${UnitOfMeasureCode}~
CTT*${NumberOfLineItems}~
SE*${NumberOfIncludedSegments}*${TransactionSetControlNumber}~
GE*${NumberOfTransactionSetsIncluded}*${GroupControlNumber}~
IEA*${NumberOfFunctionalGroupsIncluded}*${InterchangeControlNumber}~
