ISA*${AuthorizationInformationQualifier}*${AuthorizationInformation}*${SecurityInformationQualifier}*${SecurityInformation}*${InterchangeIDQualifierSender}*${InterchangeSenderID}*${InterchangeIDQualifier}*${InterchangeIDQualifierSender}*${InterchangeSenderID}*${InterchangeIDQualifier}*${InterchangeReceiverID}*${InterchangeDate}*${InterchangeTime}*${InterchangeControlStandardsIdentifier}*${InterchangeControlVersionNumber}*${InterchangeControlNumber}*${AcknowledgementRequested}*${TestIndicator}*>~
GS*SH*${ApplicationSenderCode}*${ApplicationReceiverCode}*${Date}*${Time}*${GroupControlNumber}*${ResponsibleAgencyCode}*${Version}~
ST*856*${TransactionSetControlNumber}~
BSN*${TransactionSetPurpose}*${ShipNoticeNumber}*${ShipNoticeDate}*${ShipNoticeTime}*${HierarchicalStructureCode}~
HL*${HierarchicalIDNumber}**${HierarchicalLevelCode}~
TD5*****${RoutingOriginalCourier}~
REF*${BillReferenceNumberQualifier}*${BillReferenceNumber}~
REF*${PickupReferenceNumberQualifier}*${PickupReferenceNumber}~
DTM*${DateQualifier}*${Date}~
N1*${ShipToIdentifierCode}*${ShipToName}*${ShipToIdentificationCodeQualifier}*${ShipToIdentificationCode}~
N1*${ShipFromIdentifierCode}*${ShipFromName}~
N3*${AddressInformation}*${AddressInformation2}~
N4*${CityName}*${State}*${PostalCode}*${CountryCode}~
HL*${HierarchicalIDNumber}*${HierarchicalParentIDNumber}*${HierarchicalLevelCode}~
PRF*${PurchaseOrderNumber}~
TD1*${PackingCode}*${LadingQuantity}****${WeightQualifier}*${Weight}*${UnitOfMeasure}~
REF*${ReferenceIdentificationQualifier}*${ReferenceIdentificationDescription}~
HL*${HierarchicalIDNumber}*${HierarchicalParentIDNumber}*P~
MAN*${MarksNumberQualifier}*${MarksMeasuresDescription}~
HL*${HierarchicalIDNumber}*${HierarchicalParentIDNumber}*${HierarchicalLevelCode}~
LIN**${ProductServiceQualifier}*${ProductID}*${ProductServiceQualifier2}*${ProductID2}~
SN1**${NumberOfUnitsShipped}*${UnitOfMeasure}**${QuantityOrdered}*${UnitOfMeasure}~
SLN*${AssignedIdentification}**${RelationshipCode}*${Quantity}*${UnitOfMeasure}*${UnitPrice}~
PID*${ItemDescriptionType}****${ProductDescription}~
CTT*${NumberOfLineItems}~
SE*${NumberOfIncludedSegments}*${TransactionSetControlNumber}~
GE*${NumberOfTransactionSetsIncluded}*${GroupControlNumber}~
IEA*${NumberOfFunctionalGroupsIncluded}*${InterchangeControlNumber}~